#!/bin/bash

# Retrieve the values stored in the environment variables
water_value="$WATER"
stir_value="$STIR"

# Perform the addition and convert to base "bestchol"
result_bestchol=$(printf "%o\n" $(( $((5#$(echo "$water_value" | tr 'water' '01234'))) + $((5#$(echo "$stir_value" | tr 'stir.' '01234'))) )) | tr '01234567' 'bestchol')

# Print the result
echo "The result is: $result_bestchol"
